# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
left_hip_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_hip_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

left_hip_servo_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_hip_servo_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

left_thigh_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_thigh_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

left_shin_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_shin_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

left_ankle_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_ankle_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

left_foot_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_foot_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

right_hip_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_hip_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

right_hip_servo_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_hip_servo_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

right_thigh_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_thigh_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

right_shin_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_shin_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

right_ankle_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_ankle_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

right_foot_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_foot_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0