# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: "position_controllers/JointPositionController"
  joint: servo1_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

joint2_position_controller:
  type: "position_controllers/JointPositionController"
  joint: hub2_joint
  pid:
    p: 2.0
    i: 0.5
    d: 0.0

